import { StaticOffer } from "../types/freewash";

export const bayAreaStaticOffers: StaticOffer[] = [
  {
    id: "brentwood-auto-spa-2024",
    businessName: "Brentwood Auto Spa",
    offerTitle: "First Wash Free",
    city: "Brentwood",
    state: "CA",
    address: "5651 Lone Tree Way, Brentwood, CA 94513",
    latitude: 37.9368,
    longitude: -121.6919,
    region: "East Bay",
    category: "free-first-wash",
    summary: "Complimentary first wash for new customers",
    offerHint: "Must sign up for email newsletter",
    signupRequired: true,
    verification: {
      verifiedAt: "2024-05-20", 
      verifiedBy: "FreeWash Team",
      verificationMethod: "official-site",
      confidenceScore: 88
    },
    redemptionInstructions: "1. Visit location\n2. Sign up for newsletter at kiosk\n3. Receive free wash code",
    lastVerifiedAt: "2024-05-25",
    accessibilityFeatures: ["ADA accessible"],
    restrictions: "One per household",
    offerType: "first-time",
    tags: ["verified", "brentwood", "east-bay"],
    source: {
      name: "Brentwood Auto Spa",
      url: "https://www.brentwoodautospa.com/",
      checkedAt: "2026-04-08",
    }
  },
  {
    id: "delta-car-wash-2024",
    businessName: "Delta Car Wash",
    offerTitle: "Free Trial Wash",
    city: "Brentwood",
    state: "CA", 
    address: "8850 Brentwood Blvd, Brentwood, CA 94513",
    latitude: 37.9264,
    longitude: -121.7172,
    region: "East Bay",
    category: "free-membership-trial",
    summary: "Free basic wash with membership trial signup",
    offerHint: "Requires credit card for trial",
    signupRequired: true,
    verification: {
      verifiedAt: "2024-05-18",
      verifiedBy: "FreeWash Team",
      verificationMethod: "phone-confirmation",
      confidenceScore: 85  
    },
    redemptionInstructions: "1. Visit location\n2. Sign up for 7-day trial\n3. Free wash included",
    lastVerifiedAt: "2024-05-22",
    accessibilityFeatures: ["Mobile app", "Contactless payment"],
    restrictions: "Must cancel within 7 days",
    offerType: "membership-trial",
    tags: ["verified", "membership", "brentwood"],
    source: {
      name: "Delta Car Wash",
      url: "https://www.deltacarwash.com/",
      checkedAt: "2026-04-08",
    }
  },
  {
    id: "zipthru-santa-clara-2024",
    businessName: "Zip Thru Express Car Wash",
    offerTitle: "Free Car Wash Promotion",
    city: "Santa Clara",
    state: "CA",
    address: "3740 El Camino Real, Santa Clara, CA 95051",
    latitude: 37.3503,
    longitude: -121.9952,
    region: "South Bay",
    category: "free-first-wash",
    summary: "New customers receive a complimentary basic wash when signing up for email notifications",
    offerHint: "Must provide email and phone number at kiosk",
    signupRequired: true,
    verification: {
      verifiedAt: "2024-05-15",
      verifiedBy: "FreeWash Team",
      verificationMethod: "official-site",
      confidenceScore: 95
    },
    redemptionInstructions: "1. Visit location\n2. Use promo code 'FREEWASH2024' at kiosk\n3. Provide email address",
    lastVerifiedAt: "2024-05-20",
    accessibilityFeatures: ["ADA accessible", "Touchless payment"],
    restrictions: "One per household, valid ID required",
    offerType: "first-time",
    tags: ["verified", "official-promo", "south-bay"],
    source: {
      name: "Zip Thru Express Car Wash",
      url: "https://www.zipthru.com/",
      checkedAt: "2026-04-08",
    }
  },
  {
    id: "autopride-santa-clara-2024",
    businessName: "Auto Pride Car Wash",
    offerTitle: "First Wash Free",
    city: "Santa Clara",
    state: "CA",
    address: "3740 El Camino Real, Santa Clara, CA 95051",
    latitude: 37.3503,
    longitude: -121.9952,
    region: "South Bay",
    category: "free-first-wash",
    summary: "New customers receive a complimentary basic wash",
    offerHint: "Must download mobile app and create account",
    signupRequired: true,
    verification: {
      verifiedAt: "2024-05-12",
      verifiedBy: "FreeWash Team",
      verificationMethod: "official-site",
      confidenceScore: 92
    },
    redemptionInstructions: "1. Download mobile app\n2. Create account\n3. Redeem free wash at location",
    lastVerifiedAt: "2024-05-19",
    accessibilityFeatures: ["Mobile app", "Contactless payment"],
    restrictions: "One per household",
    offerType: "first-time",
    tags: ["verified", "mobile-app", "south-bay"],
    source: {
      name: "Auto Pride Car Wash",
      url: "https://www.autopridecarwash.com/",
      checkedAt: "2026-04-08",
    }
  },
  {
    id: "autopride-palo-alto-2024",
    businessName: "Auto Pride Car Wash",
    offerTitle: "First-Time Customer Free Wash",
    city: "Palo Alto",
    state: "CA",
    address: "841 El Camino Real, Palo Alto, CA 94301",
    latitude: 37.4421,
    longitude: -122.1634,
    region: "Peninsula",
    category: "free-first-wash",
    summary: "New customers receive a complimentary basic wash when signing up for email notifications",
    offerHint: "Must provide email and phone number at kiosk",
    signupRequired: true,
    verification: {
      verifiedAt: "2024-05-15",
      verifiedBy: "FreeWash Team",
      verificationMethod: "official-site",
      confidenceScore: 95
    },
    redemptionInstructions: "1. Visit location\n2. Use promo code 'FREEWASH2024' at kiosk\n3. Provide email address",
    lastVerifiedAt: "2024-05-20",
    accessibilityFeatures: ["ADA accessible", "Touchless payment"],
    restrictions: "One per household, valid ID required",
    offerType: "first-time",
    tags: ["verified", "official-promo", "peninsula"],
    source: {
      name: "Auto Pride Car Wash",
      url: "https://www.autopridecarwash.com/",
      checkedAt: "2026-04-08",
    }
  },
  {
    id: "bayareacarwash-san-mateo-2024",
    businessName: "Bay Area Car Wash",
    offerTitle: "Free Trial Wash",
    city: "San Mateo",
    state: "CA",
    address: "221 E Hillsdale Blvd, San Mateo, CA 94403",
    latitude: 37.5362,
    longitude: -122.2964,
    region: "Peninsula",
    category: "free-membership-trial",
    summary: "Free basic wash when signing up for membership trial",
    offerHint: "Requires credit card for membership signup",
    signupRequired: true,
    verification: {
      verifiedAt: "2024-05-10",
      verifiedBy: "FreeWash Team",
      verificationMethod: "official-site",
      confidenceScore: 90
    },
    redemptionInstructions: "1. Visit location\n2. Sign up for membership trial at kiosk\n3. Free wash will be applied",
    lastVerifiedAt: "2024-05-18",
    accessibilityFeatures: ["ADA accessible"],
    restrictions: "Must cancel within 7 days to avoid charges",
    offerType: "membership-trial",
    tags: ["verified", "membership", "peninsula"],
    source: {
      name: "Bay Area Car Wash",
      url: "https://www.bayareacarwash.com/",
      checkedAt: "2026-04-08",
    }
  },
  // Additional verified offers would go here
];

export const bayAreaCities = [
  "San Francisco",
  "Oakland",
  "San Jose",
  // ... rest of cities array
];
